[package]
name = "tdd-kata"
version = "0.0.8"
authors = ["Alex-Diez <alexvic.amatory@gmail.com>"]

[lib]
name = "tdd_kata"

[[test]]
name = "test"
path = "test/lib.rs"

[dependencies.stainless]
git = "https://github.com/Alex-Diez/stainless.git"
branch = "master"

[dependencies]
clippy = "0.0.43"
expectest = "0.4.1"
regex = "0.1.52"
regex_macros = "0.1.30"
