[package]
name = "tdd-kata"
version = "0.0.1-SNAPSHOT"
authors = ["Alex-Diez <alexvic.amatory@gmail.com>"]

[lib]
name = "calc"
path = "src/calc.rs"

[[test]]
name = "unit_tests"
path = "src/tests.rs"
