[package]
name = "tdd-kata"
version = "0.0.1-SNAPSHOT"
authors = ["Alex-Diez <alexvic.amatory@gmail.com>"]

[lib]
name = "lexer"
path = "src/lexer.rs"

[[test]]
name = "unit_tests"
path = "src/tests.rs"

[dependencies]
regex = "0.1.41"
regex_macros = "0.1.23"
