[package]
name = "queue-kata"
version = "0.0.1"
authors = ["Alex-Diez <alex.dukhno@icloud.com>"]
workspace = ".."

[lib]
name = "queue_kata"

[dependencies]
clippy = {version = "*", optional = true}

[features]
default = []
