[package]
name = "bowling-kata"
version = "0.0.2"
authors = ["Alex-Diez <alex.dukhno@icloud.com>"]
workspace = ".."

[lib]
name = "bowling_kata"
path = "src/lib.rs"

[dependencies]
clippy = {version = "*", optional = true}

[features]
default = []
